export const Projects = [
  {
    id: 1,
    name: "TaskMaster",
    description: "A project management tool for teams.",
  },
  {
    id: 2,
    name: "BugTracker",
    description: "A web app to track and manage bugs.",
  },
  {
    id: 3,
    name: "TimeKeeper",
    description: "A time tracking application for freelancers.",
  },
  {
    id: 4,
    name: "InvoiceGen",
    description: "An invoicing application for small businesses.",
  },
  {
    id: 5,
    name: "EventPlanner",
    description: "A web app to plan and manage events.",
  },
  {
    id: 6,
    name: "FitnessTracker",
    description: "A fitness tracking application for individuals.",
  },
  {
    id: 7,
    name: "RecipeBook",
    description: "A web app to store and share recipes.",
  },
  {
    id: 8,
    name: "BookClub",
    description: "A platform for book club management.",
  },
  {
    id: 9,
    name: "TravelLog",
    description: "A travel logging and planning application.",
  },
  {
    id: 10,
    name: "BudgetBuddy",
    description: "A personal finance and budgeting tool.",
  },
  {
    id: 11,
    name: "StudyBuddy",
    description: "A study planning and tracking application.",
  },
  {
    id: 12,
    name: "HealthMonitor",
    description: "A health monitoring and management app.",
  },
  {
    id: 13,
    name: "PetCare",
    description: "A pet care and management application.",
  },
  {
    id: 14,
    name: "GardenPlanner",
    description: "A gardening planning and tracking tool.",
  },
  {
    id: 15,
    name: "HomeInventory",
    description: "A home inventory management application.",
  },
  {
    id: 16,
    name: "WorkoutBuddy",
    description: "A workout planning and tracking app.",
  },
  {
    id: 17,
    name: "LanguageLearner",
    description: "A language learning and practice tool.",
  },
  {
    id: 18,
    name: "MusicLibrary",
    description: "A music library management application.",
  },
  {
    id: 19,
    name: "PhotoGallery",
    description: "A photo gallery and sharing platform.",
  },
  {
    id: 20,
    name: "WeatherWatch",
    description: "A weather monitoring and alert app.",
  },
];

export const tasks = [
  {
    id: 1,
    task: [
      {
        id: 1,
        title: "Fix bug #123",
        priority: "High",
        dueDate: "2025-03-15",
        status: "Pending",
      },
      {
        id: 2,
        title: "Implement Auth",
        priority: "Medium",
        dueDate: "2025-03-18",
        status: "In Progress",
      },
      {
        id: 3,
        title: "Refactor UI",
        priority: "Low",
        dueDate: "2025-03-20",
        status: "Completed",
      },
      {
        id: 4,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-03-22",
        status: "Pending",
      },
      {
        id: 5,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-03-25",
        status: "In Progress",
      },
      {
        id: 6,
        title: "Write tests",
        priority: "Low",
        dueDate: "2025-03-28",
        status: "Completed",
      },
      {
        id: 7,
        title: "Optimize performance",
        priority: "High",
        dueDate: "2025-03-30",
        status: "Pending",
      },
      {
        id: 8,
        title: "Fix bug #456",
        priority: "Medium",
        dueDate: "2025-04-02",
        status: "In Progress",
      },
      {
        id: 9,
        title: "Refactor code",
        priority: "Low",
        dueDate: "2025-04-05",
        status: "Completed",
      },
      {
        id: 10,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-04-08",
        status: "Pending",
      },
      {
        id: 11,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-04-10",
        status: "In Progress",
      },
      {
        id: 12,
        title: "Write tests",
        priority: "Low",
        dueDate: "2025-04-12",
        status: "Completed",
      },
      {
        id: 13,
        title: "Optimize performance",
        priority: "High",
        dueDate: "2025-04-15",
        status: "Pending",
      },
      {
        id: 14,
        title: "Fix bug #789",
        priority: "Medium",
        dueDate: "2025-04-18",
        status: "In Progress",
      },
      {
        id: 15,
        title: "Refactor code",
        priority: "Low",
        dueDate: "2025-04-20",
        status: "Completed",
      },
      {
        id: 16,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-04-22",
        status: "Pending",
      },
      {
        id: 17,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-04-25",
        status: "In Progress",
      },
      {
        id: 18,
        title: "Write tests",
        priority: "Low",
        dueDate: "2025-04-28",
        status: "Completed",
      },
      {
        id: 19,
        title: "Optimize performance",
        priority: "High",
        dueDate: "2025-04-30",
        status: "Pending",
      },
      {
        id: 20,
        title: "Fix bug #1011",
        priority: "Medium",
        dueDate: "2025-05-02",
        status: "In Progress",
      },
      {
        id: 21,
        title: "Refactor code",
        priority: "Low",
        dueDate: "2025-05-05",
        status: "Completed",
      },
      {
        id: 22,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-05-08",
        status: "Pending",
      },
      {
        id: 23,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-05-10",
        status: "In Progress",
      },
      {
        id: 24,
        title: "Write tests",
        priority: "Low",
        dueDate: "2025-05-12",
        status: "Completed",
      },
      {
        id: 25,
        title: "Optimize performance",
        priority: "High",
        dueDate: "2025-05-15",
        status: "Pending",
      },
      {
        id: 26,
        title: "Fix bug #1213",
        priority: "Medium",
        dueDate: "2025-05-18",
        status: "In Progress",
      },
      {
        id: 27,
        title: "Refactor code",
        priority: "Low",
        dueDate: "2025-05-20",
        status: "Completed",
      },
      {
        id: 28,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-05-22",
        status: "Pending",
      },
      {
        id: 29,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-05-25",
        status: "In Progress",
      },
      {
        id: 30,
        title: "Write tests",
        priority: "Low",
        dueDate: "2025-05-28",
        status: "Completed",
      },
    ],
  },
  {
    id: 2,
    task: [
      {
        id: 1,
        title: "Fix bug #123",
        priority: "High",
        dueDate: "2025-03-15",
        status: "Pending",
      },
      {
        id: 2,
        title: "Implement Auth",
        priority: "Medium",
        dueDate: "2025-03-18",
        status: "In Progress",
      },
      {
        id: 3,
        title: "Refactor UI",
        priority: "Low",
        dueDate: "2025-03-20",
        status: "Completed",
      },
      {
        id: 4,
        title: "Add new feature",
        priority: "High",
        dueDate: "2025-03-22",
        status: "Pending",
      },
      {
        id: 5,
        title: "Update dependencies",
        priority: "Medium",
        dueDate: "2025-03-25",
        status: "In Progress",
      },
    ],
  },
];
